version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bbbb
      - POSTGRES_DB=employee_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local